# Generated by Django 5.1.5 on 2025-01-21 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='fk_scelta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='palletts', to='magazzino.scelta'),
        ),
    ]
