# Generated by Django 5.1.5 on 2025-01-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0002_pallet_fk_scelta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallet',
            name='pezzi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
