# Generated by Django 5.1.5 on 2025-01-23 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0003_alter_pallet_pezzi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scelta',
            options={'verbose_name': 'Scelta', 'verbose_name_plural': 'Scelte'},
        ),
        migrations.AlterModelOptions(
            name='zonamagazzino',
            options={'verbose_name': 'Zona Magazzino', 'verbose_name_plural': 'Zone Magazzino'},
        ),
    ]
